### ISSUE TITLE
[BUG] containment in sql not working

### ISSUE THREAD

**Issue by kb634** [typhon-project/typhonql#106]
**Describe the bug**

Trying to add a containment reference in mysql results in the reference to not be added (remains null with the relevant entity never created) 

**Query**

```
{
"query" : "insert Datatypes {cref: CRefer {r: 3}}"
}
``` 

**Model**

``` 
entity Datatypes {
	cref :-> CRefer[1]
}

entity CRefer {
	r : int
}
	
 relationaldb DatatypesDB {
 	tables { 
 		table{
 			DatatypesTable : Datatypes
			}
 		table{
 			CReferTable : CRefer
			}			
 	} 
 }
```

**Expected behavior**

Expected a Datatypes  entity to be created with a contained CRefer entity, the reference remains null instead.

**Comment by tvdstorm** [comment]
Support for the nested object literals in inserts has been indefinitely postponed AFAIK. The way to do this is: first create the `CRefer`, get its uuid, and then assign it to `cref` (i.e. by reference).

**Comment by kb634** [comment]
that is impossible, containments cannot be created on their own (used to just do nothing but now throws exception)

**Comment by tvdstorm** [comment]
Ok, I will have a look.

**Comment by tvdstorm** [comment]
Hi, I've looked our tests (where it works). Can you try the following: 

First add an inverse on the child (`CRefer`): 

```
datatype -> Datatypes."Datatypes.cref"[1]
```
And then insert the `CRefer` after inserting a `Datatypes` (the parent), like so:

```
insert CRefer { r: 123, datatype: #...theuuid }
```

**Comment by kb634** [comment]
thank you, it works with inclusion of an inverse.
