### ISSUE TITLE
[BUG] Multiple where clauses in Document DB

### ISSUE THREAD

**Issue by zolotas4** [typhon-project/typhonql#107]
**Describe the bug**

We are not able to apply more than one where clauses in document databases. 

**Query**
```
{
	"query" : "from VehicleWeatherData vwd select vwd.@id where vwd.VIN>12 && vwd.VIN<222"
}
```
or
```
{
	"query" : "from VehicleWeatherData vwd select vwd.@id where vwd.VIN==125 && vwd.temperature <= 4.0"
}
``` 

**Model**

``` 
entity VehicleWeatherData {
	VIN: int
	timeStamp : datetime
	vehicle_position : point
	temperature: float
	rain_Intensity: float
	solar_Intensity: int
}

documentdb DocumentDB {
	collections {
		vehicleWeatherData : VehicleWeatherData 
	}
}
```

**Expected behavior**

We expect the execution of the query to return a result set (empty or non-empty depending on the clauses values/data in the DB). Instead we receive a `500 server error` message. 

**REST API**

If the bug happens when calling the REST API:

- exact JSON body send to API: See query section above
- output of `docker-compose logs qlserver`
```
typhonql-server_1           | )
typhonql-server_1           | TyphonQL failed to handle request, msg:
typhonql-server_1           | Unsupported expression: vwd.VIN>12 && vwd.VIN<222
typhonql-server_1           | Trace:
typhonql-server_1           | |lib://typhonql/src/lang/typhonql/mongodb/Query2Mongo.rsc%7C(10892,2,<357,35>,<357,37>): "Unsupported expression: vwd.VIN\>12 && vwd.VIN\<222"
```

**Additional context**

This affects VW use case.

**Comment by tvdstorm** [comment]
Can you try  `,` instead of `&&`?

**Comment by kb634** [comment]
thank you that works

**Comment by zolotas4** [comment]
Just a follow up: `,` works on both relational and document as AND which is good. But what about OR ? || works on relational but does not work on document. Is there another symbol for OR (like `,`) that works for both?

**Comment by tvdstorm** [comment]
Both are now supported directly on MongoDB (as per b6eea37f)
