### ISSUE TITLE
"rename" evolution operators not implemented

### ISSUE THREAD

**Issue by benatspo** [typhon-project/typhonql#41]
Hi,

The following list contains the "rename" evolution operators not yet available using QL, with their corresponding syntax (discussed during a meeting in Amsterdam):
- Rename entity attribute -> syntax: `rename Address.street to streetName`
- Rename entity relation -> syntax: `rename Address.userAddress to user`
- Rename entity -> syntax: `rename Address to UserAddress`

Thank you for your help,

Pol

**Comment by tvdstorm** [comment]
These have been implemented in the meantime.
