### ISSUE TITLE
"drop relation" evolution operator not working

### ISSUE THREAD

**Issue by benatspo** [typhon-project/typhonql#42]
Hi,

I have an exception when running a "drop relation" query on the polystore.
For example, the query `drop relation Order.user` threw the following exception:

> typhon-polystore-service_1  | |jar+file:///app/libs/typhonql-headless-0.1.0-SNAPSHOT.jar!/src/lang/typhonql/Run.rsc|(5582,1,<171,70>,<171,71>)Feb 21, 2020 11:03:32 AM org.apache.catalina.core.StandardWrapperValve invoke
> typhon-polystore-service_1  | SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.rascalmpl.interpreter.staticErrors.UnexpectedType: Expected Rel, but got tuple[EId,value,Id,str,value,str,bool]
> typhon-polystore-service_1  | Advice: |http://tutor.rascal-mpl.org/Errors/Static/UnexpectedType/UnexpectedType.html|] with root cause
> typhon-polystore-service_1  | org.rascalmpl.interpreter.staticErrors.UnexpectedType: Expected Rel, but got tuple[EId,value,Id,str,value,str,bool]
> typhon-polystore-service_1  | Advice: |http://tutor.rascal-mpl.org/Errors/Static/UnexpectedType/UnexpectedType.html|
> typhon-polystore-service_1  |   at Run.?(/app/libs/typhonql-headless-0.1.0-SNAPSHOT.jar!/src/lang/typhonql/Run.rsc:171)
> typhon-polystore-service_1  |   at org.rascalmpl.interpreter.matching.IteratorFactory.checkMayOccur(IteratorFactory.java:175)

Thank you for your help,

Pol

**Comment by tvdstorm** [comment]
This should be working by now.
